name: stonekaiju4
favicon: null
layout_spectrum: 0.50592
typography_spectrum: 0.23428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#858384'
    - '#5f5f5f'
    - '#212121'
    - '#7d0305'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
