name: stonekaiju4
favicon: null
layout_spectrum: 0.50592
typography_spectrum: 0.23428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#110101'
    - '#ff0506'
    - '#833b3c'
    - '#e1c0d1'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
